"""add_todo_items_table

Revision ID: 53f28db7acbd
Revises: 5f3c750681de
Create Date: 2026-04-11 16:12:39.421800+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f28db7acbd'
down_revision: Union[str, None] = '5f3c750681de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.String(length=5), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_todo_pet', 'todo_items', ['pet_id'], unique=False)
    op.create_index('idx_todo_user_date', 'todo_items', ['user_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_todo_items_id'), 'todo_items', ['id'], unique=False)
    op.create_index(op.f('ix_todo_items_is_completed'), 'todo_items', ['is_completed'], unique=False)
    op.create_index(op.f('ix_todo_items_pet_id'), 'todo_items', ['pet_id'], unique=False)
    op.create_index(op.f('ix_todo_items_user_id'), 'todo_items', ['user_id'], unique=False)
    op.drop_index(op.f('idx_diet_plans_is_active'), table_name='diet_plans')
    op.drop_index(op.f('idx_diet_plans_pet_id'), table_name='diet_plans')
    op.create_index(op.f('ix_diet_plans_pet_id'), 'diet_plans', ['pet_id'], unique=False)
    op.drop_constraint(op.f('diet_plans_pet_id_fkey'), 'diet_plans', type_='foreignkey')
    op.create_foreign_key(None, 'diet_plans', 'pets', ['pet_id'], ['id'])
    op.drop_index(op.f('idx_meal_records_meal_type'), table_name='meal_records')
    op.drop_index(op.f('idx_meal_records_pet_date'), table_name='meal_records')
    op.drop_index(op.f('idx_meal_records_pet_id'), table_name='meal_records')
    op.drop_index(op.f('idx_pets_type'), table_name='pets')
    op.drop_index(op.f('idx_pets_user_active'), table_name='pets')
    op.drop_index(op.f('idx_pets_user_id'), table_name='pets')
    op.alter_column('users', 'is_pro',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_pro',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_pets_user_id'), 'pets', ['user_id'], unique=False)
    op.create_index(op.f('idx_pets_user_active'), 'pets', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_pets_type'), 'pets', ['type'], unique=False)
    op.create_index(op.f('idx_meal_records_pet_id'), 'meal_records', ['pet_id'], unique=False)
    op.create_index(op.f('idx_meal_records_pet_date'), 'meal_records', ['pet_id', 'meal_date'], unique=False)
    op.create_index(op.f('idx_meal_records_meal_type'), 'meal_records', ['meal_type'], unique=False)
    op.drop_constraint(None, 'diet_plans', type_='foreignkey')
    op.create_foreign_key(op.f('diet_plans_pet_id_fkey'), 'diet_plans', 'pets', ['pet_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_diet_plans_pet_id'), table_name='diet_plans')
    op.create_index(op.f('idx_diet_plans_pet_id'), 'diet_plans', ['pet_id'], unique=False)
    op.create_index(op.f('idx_diet_plans_is_active'), 'diet_plans', ['is_active'], unique=False)
    op.drop_index(op.f('ix_todo_items_user_id'), table_name='todo_items')
    op.drop_index(op.f('ix_todo_items_pet_id'), table_name='todo_items')
    op.drop_index(op.f('ix_todo_items_is_completed'), table_name='todo_items')
    op.drop_index(op.f('ix_todo_items_id'), table_name='todo_items')
    op.drop_index('idx_todo_user_date', table_name='todo_items')
    op.drop_index('idx_todo_pet', table_name='todo_items')
    op.drop_table('todo_items')
    # ### end Alembic commands ###
